name: CI/CD

on: [push, pull_request] # Aciona o workflow em pushes e pull requests

jobs:
  build:
    runs-on: ubuntu-latest # Define o ambiente onde o job será executado

    steps:
      # Baixa o código do repositório
      - uses: actions/checkout@v2

      # Configura o Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Versão do Node.js

      # Instala as dependências do projeto
      - name: Install dependencies
        run: npm install

      # Executa testes
      - name: Run tests
        run: npm test
